# Generated by Django 3.2 on 2021-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.IntegerField(default=0),
        ),
    ]
