# Generated by Django 3.2 on 2021-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='flag_active',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
