# Generated by Django 3.2 on 2021-04-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='flag_active',
            new_name='active',
        ),
    ]
